name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: cimg/python:3.8  # Use CircleCI's Python 3.8 image as Docker container

    steps:
      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Chrome dependencies
      - name: Install Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip
          sudo apt-get install -y libx11-dev libgconf-2-4 libnss3 libgdk-pixbuf2.0-0 libxcomposite1 libxdamage1 libxi6 libxtst6
          sudo apt-get install -y libasound2 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdbus-1-3 libgdk-pixbuf2.0-0
          sudo apt-get install -y libnspr4 libnss3 libxrandr2

      # Install Google Chrome
      - name: Install Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || true
          sudo apt-get -f install -y  # Fix any missing dependencies

      # Install ChromeDriver based on Chrome version
      - name: Install ChromeDriver
        run: |
          # Extract the full version of Chrome (e.g., 94.0.4606.81)
          CHROME_VERSION=$(google-chrome-stable --version | awk '{print $3}' | cut -d '.' -f 1-3)
          echo "Detected Chrome version: $CHROME_VERSION"
          
          # Fetch the corresponding ChromeDriver version using the correct API
          CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
          echo "Detected ChromeDriver version: $CHROMEDRIVER_VERSION"
          
          # Check if the ChromeDriver version is empty or not found
          if [ -z "$CHROMEDRIVER_VERSION" ]; then
            echo "Error: Unable to find a matching ChromeDriver version for Chrome version $CHROME_VERSION"
            exit 1
          fi
          
          # Download ChromeDriver and install it
          wget https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.204/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/

      # Install Python dependencies from requirements.txt
      - name: Install dependencies from requirements.txt
        run: |
          python -m venv venv
          . venv/bin/activate  # Activate the virtual environment (using dot for POSIX compatibility)
          pip install --upgrade pip
          pip install -r requirements.txt  # Install all dependencies listed in requirements.txt

      # Run the test script
      - name: Run tests
        run: |
          . venv/bin/activate  # Activate the virtual environment (using dot for POSIX compatibility)
          pytest ./testFiles        # Run the tests with pytest
